"""
AvaTax Software Development Kit for Python.

   Copyright 2022 Avalara, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

    AvaTax API
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator) 

@author     Sachin Baijal <sachin.baijal@avalara.com>
@author     Jonathan Wenger <jonathan.wenger@avalara.com>
@copyright  2022 Avalara, Inc.
@license    https://www.apache.org/licenses/LICENSE-2.0
@version    0.1.1
@link       https://github.com/avadev/AvaTax-REST-V3-Python-SDK
"""

import re  # noqa: F401
import sys  # noqa: F401

from Avalara.SDK.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from Avalara.SDK.exceptions import ApiAttributeError



class ErrorDetail(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('code',): {
            'SERVERCONFIGURATION': "ServerConfiguration",
            'ACCOUNTINVALIDEXCEPTION': "AccountInvalidException",
            'COMPANYINVALIDEXCEPTION': "CompanyInvalidException",
            'ENTITYNOTFOUNDERROR': "EntityNotFoundError",
            'VALUEREQUIREDERROR': "ValueRequiredError",
            'RANGEERROR': "RangeError",
            'RANGECOMPAREERROR': "RangeCompareError",
            'RANGESETERROR': "RangeSetError",
            'TAXPAYERNUMBERREQUIRED': "TaxpayerNumberRequired",
            'ENTITYLIMITEXCEEDED': "EntityLimitExceeded",
            'COMMONPASSWORD': "CommonPassword",
            'WEAKPASSWORD': "WeakPassword",
            'STRINGLENGTHERROR': "StringLengthError",
            'MAXSTRINGLENGTHERROR': "MaxStringLengthError",
            'EMAILVALIDATIONERROR': "EmailValidationError",
            'EMAILMISSINGERROR': "EmailMissingError",
            'INVALIDQUERYFIELD': "InvalidQueryField",
            'INVALIDQUERYVALUE': "InvalidQueryValue",
            'SYNTAXERROR': "SyntaxError",
            'TOOMANYPARAMETERSERROR': "TooManyParametersError",
            'UNTERMINATEDVALUEERROR': "UnterminatedValueError",
            'DELETEUSERSELFERROR': "DeleteUserSelfError",
            'OLDPASSWORDINVALID': "OldPasswordInvalid",
            'CANNOTCHANGEPASSWORD': "CannotChangePassword",
            'READONLY': "ReadOnly",
            'DATEFORMATERROR': "DateFormatError",
            'NODEFAULTCOMPANY': "NoDefaultCompany",
            'ACCOUNTTYPENOTSUPPORTED': "AccountTypeNotSupported",
            'INVALIDAUTHENTICATIONTYPE': "InvalidAuthenticationType",
            'AUTHENTICATIONEXCEPTION': "AuthenticationException",
            'AUTHORIZATIONEXCEPTION': "AuthorizationException",
            'VALIDATIONEXCEPTION': "ValidationException",
            'INACTIVEUSERERROR': "InactiveUserError",
            'AUTHENTICATIONINCOMPLETE': "AuthenticationIncomplete",
            'BASICAUTHINCORRECT': "BasicAuthIncorrect",
            'IDENTITYSERVERERROR': "IdentityServerError",
            'BEARERTOKENINVALID': "BearerTokenInvalid",
            'MODELREQUIREDEXCEPTION': "ModelRequiredException",
            'ACCOUNTEXPIREDEXCEPTION': "AccountExpiredException",
            'BEARERTOKENNOTSUPPORTED': "BearerTokenNotSupported",
            'INVALIDSECURITYROLE': "InvalidSecurityRole",
            'INVALIDREGISTRARACTION': "InvalidRegistrarAction",
            'REMOTESERVERERROR': "RemoteServerError",
            'NOFILTERCRITERIAEXCEPTION': "NoFilterCriteriaException",
            'OPENCLAUSEEXCEPTION': "OpenClauseException",
            'JSONFORMATERROR': "JsonFormatError",
            'INVALIDDECIMALVALUE': "InvalidDecimalValue",
            'PERMISSIONREQUIRED': "PermissionRequired",
            'UNHANDLEDEXCEPTION': "UnhandledException",
            'INACTIVEACCOUNT': "InactiveAccount",
            'LINKAGENOTALLOWED': "LinkageNotAllowed",
            'LINKAGESTATUSUPDATENOTSUPPORTED': "LinkageStatusUpdateNotSupported",
            'REPORTINGCOMPANYMUSTHAVECONTACTSERROR': "ReportingCompanyMustHaveContactsError",
            'COMPANYPROFILENOTSET': "CompanyProfileNotSet",
            'CANNOTASSIGNUSERTOCOMPANY': "CannotAssignUserToCompany",
            'MUSTASSIGNUSERTOCOMPANY': "MustAssignUserToCompany",
            'INVALIDTAXTYPEMAPPING': "InvalidTaxTypeMapping",
            'MODELSTATEINVALID': "ModelStateInvalid",
            'DATERANGEERROR': "DateRangeError",
            'INVALIDDATERANGEERROR': "InvalidDateRangeError",
            'RULEMUSTHAVETAXCODE': "RuleMustHaveTaxCode",
            'RULETYPERESTRICTED': "RuleTypeRestricted",
            'ALLJURISRULELIMITS': "AllJurisRuleLimits",
            'INVALIDCOMPANYLOCATIONSETTING': "InvalidCompanyLocationSetting",
            'INVALIDADJUSTMENTTYPE': "InvalidAdjustmentType",
            'DELETEINFORMATION': "DeleteInformation",
            'DISABLEAUTHENTICATIONFORSAMLBASEDACCOUNTS': "DisableAuthenticationForSamlBasedAccounts",
            'DISABLERESETPASSWORDFORSAMLBASEDACCOUNTS': "DisableResetPasswordForSamlBasedAccounts",
            'OUTOFRANGE': "OutOfRange",
            'UNSPECIFIEDTIMEZONE': "UnspecifiedTimeZone",
            'CANNOTCREATEDELETEDOBJECTS': "CannotCreateDeletedObjects",
            'CANNOTMODIFYDELETEDOBJECTS': "CannotModifyDeletedObjects",
            'RETURNNAMENOTFOUND': "ReturnNameNotFound",
            'INVALIDADDRESSTYPEANDCATEGORY': "InvalidAddressTypeAndCategory",
            'DEFAULTCOMPANYLOCATION': "DefaultCompanyLocation",
            'INVALIDCOUNTRY': "InvalidCountry",
            'INVALIDCOUNTRYREGION': "InvalidCountryRegion",
            'BRAZILVALIDATIONERROR': "BrazilValidationError",
            'BRAZILEXEMPTVALIDATIONERROR': "BrazilExemptValidationError",
            'BRAZILPISCOFINSERROR': "BrazilPisCofinsError",
            'JURISDICTIONNOTFOUNDERROR': "JurisdictionNotFoundError",
            'MEDICALEXCISEERROR': "MedicalExciseError",
            'RATEDEPENDSTAXABILITYERROR': "RateDependsTaxabilityError",
            'INVALIDRATETYPECODE': "InvalidRateTypeCode",
            'RATETYPENOTSUPPORTED': "RateTypeNotSupported",
            'CANNOTUPDATENESTEDOBJECTS': "CannotUpdateNestedObjects",
            'UPCCODEINVALIDCHARS': "UPCCodeInvalidChars",
            'UPCCODEINVALIDLENGTH': "UPCCodeInvalidLength",
            'INCORRECTPATHERROR': "IncorrectPathError",
            'INVALIDJURISDICTIONTYPE': "InvalidJurisdictionType",
            'MUSTCONFIRMRESETLICENSEKEY': "MustConfirmResetLicenseKey",
            'DUPLICATECOMPANYCODE': "DuplicateCompanyCode",
            'TINFORMATERROR': "TINFormatError",
            'DUPLICATENEXUSERROR': "DuplicateNexusError",
            'UNKNOWNNEXUSERROR': "UnknownNexusError",
            'PARENTNEXUSNOTFOUND': "ParentNexusNotFound",
            'INVALIDTAXCODETYPE': "InvalidTaxCodeType",
            'CANNOTACTIVATECOMPANY': "CannotActivateCompany",
            'DUPLICATEENTITYPROPERTY': "DuplicateEntityProperty",
            'REPORTINGENTITYERROR': "ReportingEntityError",
            'INVALIDRETURNOPERATIONERROR': "InvalidReturnOperationError",
            'CANNOTDELETECOMPANY': "CannotDeleteCompany",
            'COUNTRYOVERRIDESNOTAVAILABLE': "CountryOverridesNotAvailable",
            'JURISDICTIONOVERRIDEMISMATCH': "JurisdictionOverrideMismatch",
            'DUPLICATESYSTEMTAXCODE': "DuplicateSystemTaxCode",
            'SSTOVERRIDESNOTAVAILABLE': "SSTOverridesNotAvailable",
            'NEXUSDATEMISMATCH': "NexusDateMismatch",
            'NEXUSPARENTDATEMISMATCH': "NexusParentDateMismatch",
            'BEARERTOKENPARSEUSERIDERROR': "BearerTokenParseUserIdError",
            'RETRIEVEUSERERROR': "RetrieveUserError",
            'INVALIDCONFIGURATIONSETTING': "InvalidConfigurationSetting",
            'INVALIDCONFIGURATIONVALUE': "InvalidConfigurationValue",
            'INVALIDENUMVALUE': "InvalidEnumValue",
            'TAXCODEASSOCIATEDTAXRULE': "TaxCodeAssociatedTaxRule",
            'CANNOTSWITCHACCOUNTID': "CannotSwitchAccountId",
            'REQUESTINCOMPLETE': "RequestIncomplete",
            'ACCOUNTNOTNEW': "AccountNotNew",
            'PASSWORDLENGTHINVALID': "PasswordLengthInvalid",
            'INVALIDPAGEKEY': "InvalidPageKey",
            'INVALIDECMSOVERRIDECODE': "InvalidEcmsOverrideCode",
            'ACCOUNTDOESNOTEXIST': "AccountDoesNotExist",
            'INVALIDTAXTYPE': "InvalidTaxType",
            'INCORRECTFIELDVALUE': "IncorrectFieldValue",
            'LEADINGORTRAILINGEXCEPTION': "LeadingOrTrailingException",
            'NOTENOUGHADDRESSESINFO': "NotEnoughAddressesInfo",
            'REPORTNOTINITIATED': "ReportNotInitiated",
            'FAILEDTOBUILDREPORT': "FailedToBuildReport",
            'REPORTNOTFINISHED': "ReportNotFinished",
            'FAILEDTODOWNLOADREPORT': "FailedToDownloadReport",
            'MALFORMEDFILTEREXCEPTION': "MalformedFilterException",
            'EXPECTEDCONJUNCTIONERROR': "ExpectedConjunctionError",
            'CRITERIANOTSUPPORTEDERROR': "CriteriaNotSupportedError",
            'COMPANYACCOUNTANDPARENTACCOUNTMISMATCH': "CompanyAccountAndParentAccountMismatch",
            'INVALIDFILECONTENTTYPE': "InvalidFileContentType",
            'REQUESTTOOLARGE': "RequestTooLarge",
            'ECMSDISABLED': "EcmsDisabled",
            'UNKNOWNCONJUNCTIONERROR': "UnknownConjunctionError",
            'NOLINESDISCOUNTED': "NoLinesDiscounted",
            'FAILEDTODELETE': "FailedToDelete",
            'CIRCULARCOMPANYHIERARCHIES': "CircularCompanyHierarchies",
            'DUPLICATEENTRY': "DuplicateEntry",
            'DUPLICATEFIELDNAMEINORDERBY': "DuplicateFieldNameInOrderBy",
            'CANNOTADJUSTDOCUMENTTYPE': "CannotAdjustDocumentType",
            'USERNOACCESS': "UserNoAccess",
            'INVALIDENTRY': "InvalidEntry",
            'TRANSACTIONALREADYCANCELLED': "TransactionAlreadyCancelled",
            'QUERYPARAMETEROUTOFRANGE': "QueryParameterOutOfRange",
            'BATCHSALESAUDITMUSTBEZIPPEDERROR': "BatchSalesAuditMustBeZippedError",
            'BATCHZIPMUSTCONTAINONEFILEERROR': "BatchZipMustContainOneFileError",
            'BATCHINVALIDFILETYPEERROR': "BatchInvalidFileTypeError",
            'BATCHCANNOTSAVEBATCHFILE': "BatchCannotSaveBatchFile",
            'BATCHCANNOTGETBATCHFILE': "BatchCannotGetBatchFile",
            'BATCHCANNOTDELETEBATCHFILE': "BatchCannotDeleteBatchFile",
            'BATCHMUSTCONTAINONEFILE': "BatchMustContainOneFile",
            'MISSINGBATCHFILECONTENT': "MissingBatchFileContent",
            'BATCHCANNOTBEDELETEDWHILEPROCESSING': "BatchCannotBeDeletedWhileProcessing",
            'INTERNALSERVERERROR': "InternalServerError",
            'POINTOFSALEFILESIZE': "PointOfSaleFileSize",
            'POINTOFSALESETUP': "PointOfSaleSetup",
            'INVALIDINPUTDATE': "InvalidInputDate",
            'GETTAXERROR': "GetTaxError",
            'ADDRESSCONFLICTEXCEPTION': "AddressConflictException",
            'DOCUMENTCODECONFLICT': "DocumentCodeConflict",
            'MISSINGADDRESS': "MissingAddress",
            'INVALIDPARAMETERVALUE': "InvalidParameterValue",
            'FETCHLIMIT': "FetchLimit",
            'INVALIDADDRESS': "InvalidAddress",
            'ADDRESSLOCATIONNOTFOUND': "AddressLocationNotFound",
            'MISSINGLINE': "MissingLine",
            'INVALIDADDRESSTEXTCASE': "InvalidAddressTextCase",
            'DOCUMENTNOTCOMMITTED': "DocumentNotCommitted",
            'INVALIDDOCUMENTTYPESTOFETCH': "InvalidDocumentTypesToFetch",
            'TIMEOUTREQUESTED': "TimeoutRequested",
            'INVALIDPOSTALCODE': "InvalidPostalCode",
            'INVALIDSUBSCRIPTIONDESCRIPTION': "InvalidSubscriptionDescription",
            'INVALIDSUBSCRIPTIONTYPEID': "InvalidSubscriptionTypeId",
            'CANNOTCHANGEFILINGSTATUS': "CannotChangeFilingStatus",
            'FEINFORMATERROR': "FEINFormatError",
            'SERVERUNREACHABLE': "ServerUnreachable",
            'SUBSCRIPTIONREQUIRED': "SubscriptionRequired",
            'ACCOUNTEXISTS': "AccountExists",
            'INVITATIONONLY': "InvitationOnly",
            'ACCOUNTNOTWHITELISTED': "AccountNotWhitelisted",
            'FREETRIALNOTAVAILABLE': "FreeTrialNotAvailable",
            'ACCOUNTEXISTSDIFFERENTEMAIL': "AccountExistsDifferentEmail",
            'AVALARAIDENTITYAPIERROR': "AvalaraIdentityApiError",
            'INVALIDIPADDRESS': "InvalidIPAddress",
            'OFFERCODEALREADYAPPLIED': "OfferCodeAlreadyApplied",
            'ACCOUNTALREADYEXISTS': "AccountAlreadyExists",
            'LICENSEKEYNAMEALREADYEXISTSFORACCOUNT': "LicenseKeyNameAlreadyExistsForAccount",
            'USERALREADYEXIST': "UserAlreadyExist",
            'USERNOTFOUND': "UserNotFound",
            'USERMANAGEMENTEXCEPTION': "UserManagementException",
            'REFUNDTYPEANDPERCENTAGEMISMATCH': "RefundTypeAndPercentageMismatch",
            'INVALIDDOCUMENTTYPEFORREFUND': "InvalidDocumentTypeForRefund",
            'REFUNDTYPEANDLINEMISMATCH': "RefundTypeAndLineMismatch",
            'REFUNDLINESREQUIRED': "RefundLinesRequired",
            'INVALIDREFUNDTYPE': "InvalidRefundType",
            'REFUNDPERCENTAGEFORTAXONLY': "RefundPercentageForTaxOnly",
            'LINENOOUTOFRANGE': "LineNoOutOfRange",
            'REFUNDPERCENTAGEOUTOFRANGE': "RefundPercentageOutOfRange",
            'REFUNDPERCENTAGEMISSING': "RefundPercentageMissing",
            'MUSTUSECREATETRANSACTION': "MustUseCreateTransaction",
            'MUSTACCEPTTERMSANDCONDITIONS': "MustAcceptTermsAndConditions",
            'FILINGCALENDARCANNOTBEDELETED': "FilingCalendarCannotBeDeleted",
            'INVALIDEFFECTIVEDATE': "InvalidEffectiveDate",
            'NONOUTLETFORM': "NonOutletForm",
            'OVERLAPPINGFILINGCALENDAR': "OverlappingFilingCalendar",
            'FILINGCALENDARCANNOTBEEDITED': "FilingCalendarCannotBeEdited",
            'CANNOTMODIFYLOCKEDTRANSACTION': "CannotModifyLockedTransaction",
            'LINEALREADYEXISTS': "LineAlreadyExists",
            'LINEDOESNOTEXIST': "LineDoesNotExist",
            'LINESNOTSPECIFIED': "LinesNotSpecified",
            'LINEDETAILSDOESNOTEXIST': "LineDetailsDoesNotExist",
            'CANNOTCREATETRANSACTIONWITHDELETEDDATASOURCE': "CannotCreateTransactionWithDeletedDataSource",
            'SHIPTOREGIONREQUIREDWITHDATASOURCE': "ShipToRegionRequiredWithDataSource",
            'INVALIDBUSINESSTYPE': "InvalidBusinessType",
            'CANNOTMODIFYEXEMPTCERT': "CannotModifyExemptCert",
            'CERTIFICATESERROR': "CertificatesError",
            'MISSINGREQUIREDFIELDS': "MissingRequiredFields",
            'CERTIFICATESNOTSETUP': "CertificatesNotSetup",
            'CONFLICTINGEXPOSUREZONE': "ConflictingExposureZone",
            'MISSINGFIELDTOCREATEEXPOSUREZONE': "MissingFieldToCreateExposureZone",
            'MISSINGEXEMPTREASON': "MissingExemptReason",
            'INVALIDEXEMPTREASON': "InvalidExemptReason",
            'INVALIDEXEMPTIONOPERATION': "InvalidExemptionOperation",
            'CONFLICTINGFIELDS': "ConflictingFields",
            'INVALIDPDFORIMAGEFILE': "InvalidPdfOrImageFile",
            'INVALIDCOVERLETTERTITLE': "InvalidCoverLetterTitle",
            'ACCOUNTNOTPROVISIONED': "AccountNotProvisioned",
            'INVALIDREQUESTCONTENTTYPE': "InvalidRequestContentType",
            'EXEMPTIONPAGINATIONLIMITS': "ExemptionPaginationLimits",
            'EXEMPTIONSORTLIMITS': "ExemptionSortLimits",
            'CUSTOMERCANTBEBOTHSHIPTOANDBILLTO': "CustomerCantBeBothShipToAndBillTo",
            'BILLTOCUSTOMEREXPECTED': "BillToCustomerExpected",
            'SHIPTOCUSTOMEREXPECTED': "ShipToCustomerExpected",
            'ECMSSSTCERTSREQUIRED': "EcmsSstCertsRequired",
            'TRANSACTIONNOTCANCELLED': "TransactionNotCancelled",
            'TOOMANYTRANSACTIONS': "TooManyTransactions",
            'ONLYTAXDATEOVERRIDEISALLOWED': "OnlyTaxDateOverrideIsAllowed",
            'TRANSACTIONALREADYEXISTS': "TransactionAlreadyExists",
            'DATEMISMATCH': "DateMismatch",
            'INVALIDDOCUMENTSTATUSFORVERIFY': "InvalidDocumentStatusForVerify",
            'TOTALAMOUNTMISMATCH': "TotalAmountMismatch",
            'TOTALTAXMISMATCH': "TotalTaxMismatch",
            'INVALIDDOCUMENTTYPE': "InvalidDocumentType",
            'MULTIDOCUMENTPARTIALLYLOCKED': "MultiDocumentPartiallyLocked",
            'TRANSACTIONISCOMMITTED': "TransactionIsCommitted",
            'INVALIDDOCUMENTSTATUS': "InvalidDocumentStatus",
            'COMMSCONFIGCLIENTIDMISSING': "CommsConfigClientIdMissing",
            'COMMSCONFIGCLIENTIDBADVALUE': "CommsConfigClientIdBadValue",
            'ACCOUNTINNEWSTATUSEXCEPTION': "AccountInNewStatusException",
            'WORKSHEETEXCEPTION': "WorksheetException",
            'INVALIDACCOUNTOVERRIDE': "InvalidAccountOverride",
            'ACCOUNTOVERRIDENOTAUTHORIZED': "AccountOverrideNotAuthorized",
            'FIELDNOTQUERYABLEERROR': "FieldNotQueryableError",
            'USERNAMEREQUIRED': "UsernameRequired",
            'INVALIDAUDITMESSAGE': "InvalidAuditMessage",
            'FIELDNOTORDERABLEERROR': "FieldNotOrderableError",
            'CANNOTDELETEPARENTBEFORECHILDNEXUS': "CannotDeleteParentBeforeChildNexus",
            'NEXUSCHILDDATEMISMATCH': "NexusChildDateMismatch",
            'REMOTEVALIDATIONERROR': "RemoteValidationError",
            'CANNOTMODIFYSSTNEXUS': "CannotModifySstNexus",
            'INVALIDLOCALNEXUSTYPEID': "InvalidLocalNexusTypeId",
            'ADVANCEDRULEREQUESTRULEERROR': "AdvancedRuleRequestRuleError",
            'ADVANCEDRULERESPONSERULEERROR': "AdvancedRuleResponseRuleError",
            'ADVANCEDRULEERROR': "AdvancedRuleError",
            'TAXRULEREQUIRESNEXUS': "TaxRuleRequiresNexus",
            'UPCCODENOTUNIQUE': "UPCCodeNotUnique",
            'TAXCODEASSOCIATEDWITHITEMCODENOTFOUND': "TaxCodeAssociatedWithItemCodeNotFound",
            'DUPLICATESYSTEMFORITEM': "DuplicateSystemForItem",
            'CANNOTDISMISSGLOBALNOTIFICATION': "CannotDismissGlobalNotification",
            'CANNOTUPDATEACCOUNTTYPEID': "CannotUpdateAccountTypeId",
            'TAXPAYERNUMBERISREQUIRED': "TaxpayerNumberIsRequired",
            'REQUESTLIMITEXCEEDED': "RequestLimitExceeded",
            'CONCURRENTREQUESTLIMITEXCEEDED': "ConcurrentRequestLimitExceeded",
            'INVALIDDOCUMENTTYPEFORINSPECT': "InvalidDocumentTypeForInspect",
            'SERVICENOTREADY': "ServiceNotReady",
            'UPDATELOCATIONREMITTANCEMISMATCHTYPEANDCATEGORY': "UpdateLocationRemittanceMismatchTypeAndCategory",
            'UPDATELOCATIONREMITTANCECHECKEXISTINGEFFECTIVEDATEERROR': "UpdateLocationRemittanceCheckExistingEffectiveDateError",
            'UPDATELOCATIONREMITTANCECHECKEXISTINGENDDATEERROR': "UpdateLocationRemittanceCheckExistingEndDateError",
            'ERRORCOUNTLIMITEXCEEDEDERROR': "ErrorCountLimitExceededError",
            'RATELIMITEXCEEDEDERROR': "RateLimitExceededError",
            'TAXCODEANDTAXCODEIDMISSING': "TaxCodeAndTaxCodeIdMissing",
            'NEXUSALREADYEXISTS': "NexusAlreadyExists",
            'INVALIDADDRESSTYPEANDMARKETPLACEOUSIDEUSAFLAG': "InvalidAddressTypeAndMarketPlaceOusideUsaFlag",
            'INVALIDSETTINGSET': "InvalidSettingSet",
            'INVALIDSETTINGNAME': "InvalidSettingName",
            'INVALIDSETTINGVALUE': "InvalidSettingValue",
            'TOOMANYUSERDEFINEDFIELDS': "TooManyUserDefinedFields",
            'DUPLICATEUSERDEFINEDFIELDSFOUND': "DuplicateUserDefinedFieldsFound",
            'INVALIDNAMEFORUSERDEFINEDFIELD': "InvalidNameForUserDefinedField",
            'INVALIDRESTRICTIONTYPE': "InvalidRestrictionType",
            'INVALIDPARAMETER': "InvalidParameter",
            'INVALIDSYSTEMCODE': "InvalidSystemCode",
            'UNSUPPORTEDFILEFORMAT': "UnsupportedFileFormat",
            'UNSUPPORTEDOUTPUTFILETYPE': "UnsupportedOutputFileType",
            'TAXPROFILENOTPROVIDED': "TaxProfileNotProvided",
            'INVALIDTAXPROFILE': "InvalidTaxProfile",
            'COMPANYTAXPROFILEENTRYREQUIRED': "CompanyTaxProfileEntryRequired",
            'ERRORREADINGTAXPROFILEENTRY': "ErrorReadingTaxProfileEntry",
            'TRACEDATANOTAVAILABLE': "TraceDataNotAvailable",
            'INVALIDPARAMETERUNITMEASUREMENTTYPE': "InvalidParameterUnitMeasurementType",
            'PARAMETERUNITREQUIRED': "ParameterUnitRequired",
            'INVALIDPARAMETERVALUEDATATYPE': "InvalidParameterValueDataType",
            'INVALIDPARAMETERATTRIBUTETYPE': "InvalidParameterAttributeType",
            'SUBSCRIPTIONREQUIREDFORPARAMETER': "SubscriptionRequiredForParameter",
            'INVALIDACCOUNTTYPE': "InvalidAccountType",
            'INVALIDFIRMSUBSCRIPTIONS': "InvalidFirmSubscriptions",
            'GENERICTAXCODEFORITEM': "GenericTaxCodeForItem",
            'CANNOTCERTIFYCOMPANY': "CannotCertifyCompany",
            'NOVOIDEDDOCUMENTS': "NoVoidedDocuments",
            'INADEQUATECOMMITTEDDOCUMENTS': "InadequateCommittedDocuments",
            'DOCUMENTCODEISGUID': "DocumentCodeIsGuid",
            'CUSTOMERVENDORCODEISGUID': "CustomerVendorCodeIsGuid",
            'INADEQUATEDOCUMENTLINECOUNT': "InadequateDocumentLineCount",
            'SAMEDOCUMENTDESCRIPTION': "SameDocumentDescription",
            'NOEXEMPTIONNOORCUSTOMERUSAGETYPE': "NoExemptionNoOrCustomerUsageType",
            'INADEQUATEUNIQUEADDRESSES': "InadequateUniqueAddresses",
            'ITEMCODESAREALLSAME': "ItemCodesAreAllSame",
            'TAXCODESAREALLSAME': "TaxCodesAreAllSame",
            'LOCATIONCODENOTUSED': "LocationCodeNotUsed",
            'REPEATEDLINESINDOCUMENT': "RepeatedLinesInDocument",
            'TAXDATEOVERRIDEANDNEGATIVELINEAMOUNT': "TaxDateOverrideAndNegativeLineAmount",
            'ALLUSDCURRENCYCODES': "AllUSDCurrencyCodes",
            'NOVATBUYERID': "NoVATBuyerId",
            'ALLUSCOUNTRYCODES': "AllUSCountryCodes",
            'NODOCUMENTSTOTEST': "NoDocumentsToTest",
            'NOSHIPPINGCHARGE': "NoShippingCharge",
            'FAILEDTOUPDATECOMPANYLOCATION': "FailedToUpdateCompanyLocation",
            'COMPANYLOCATIONDATERANGEOVERLAP': "CompanyLocationDateRangeOverlap",
            'FIELDLENGTHERROR': "FieldLengthError",
            'INPUTCONTAINSBLACKLISTEDCHARACTERS': "InputContainsBlacklistedCharacters",
            'CANNOTCREATENESTEDOBJECTS': "CannotCreateNestedObjects",
            'USERSUBJECTIDNOTUPDATED': "UserSubjectIdNotUpdated",
            'BATCHTRANSACTIONTYPEERROR': "BatchTransactionTypeError",
            'BATCHTRANSACTIONLINELIMITEXCEEDED': "BatchTransactionLineLimitExceeded",
            'BATCHCOMPANYIDANDCOMPANYCODEMISMATCH': "BatchCompanyIdAndCompanyCodeMismatch",
            'BATCHCANNOTBECANCELLEDSTATUSERROR': "BatchCannotBeCancelledStatusError",
            'BATCHCANNOTBECANCELLEDFORMATERROR': "BatchCannotBeCancelledFormatError",
            'BATCHTYPENOTSUPPORTED': "BatchTypeNotSupported",
            'INVALIDPARAMETERDATATYPE': "InvalidParameterDataType",
            'TAGDOESNOTEXIST': "TagDoesNotExist",
            'OBJECTDELETED': "ObjectDeleted",
            'ASSOCIATEDOBJECTSDELETED': "AssociatedObjectsDeleted",
            'CANNOTDOWNLOADREPORT': "CannotDownloadReport",
            'INVALIDUNITOFBASIS': "InvalidUnitOfBasis",
            'NOTAPPLICABLEUNITOFBASIS': "NotApplicableUnitOfBasis",
            'INVALIDRATETYPETAXTYPEMAPPING': "InvalidRateTypeTaxTypeMapping",
            'INVALIDTAXTYPEGROUP': "InvalidTaxTypeGroup",
            'INVALIDTAXSUBTYPE': "InvalidTaxSubType",
            'INVALIDPRODUCTTYPEID': "InvalidProductTypeId",
            'INVALIDTAXRULETYPE': "InvalidTaxRuleType",
            'INVALIDHSCODE': "InvalidHsCode",
            'NOTAPPLICABLETAXTYPE': "NotApplicableTaxType",
            'INVALIDTAXTYPECODE': "InvalidTaxTypeCode",
            'CONTENTACCESSDENIED': "ContentAccessDenied",
            'CONTENTNOTFOUND': "ContentNotFound",
        },
        ('severity',): {
            'SUCCESS': "Success",
            'WARNING': "Warning",
            'ERROR': "Error",
            'EXCEPTION': "Exception",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'code': (str,),  # noqa: E501
            'number': (int,),  # noqa: E501
            'message': (str,),  # noqa: E501
            'description': (str,),  # noqa: E501
            'fault_code': (str,),  # noqa: E501
            'fault_sub_code': (str,),  # noqa: E501
            'help_link': (str,),  # noqa: E501
            'refers_to': (str,),  # noqa: E501
            'severity': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'code': 'code',  # noqa: E501
        'number': 'number',  # noqa: E501
        'message': 'message',  # noqa: E501
        'description': 'description',  # noqa: E501
        'fault_code': 'faultCode',  # noqa: E501
        'fault_sub_code': 'faultSubCode',  # noqa: E501
        'help_link': 'helpLink',  # noqa: E501
        'refers_to': 'refersTo',  # noqa: E501
        'severity': 'severity',  # noqa: E501
    }

    read_only_vars = {
        'help_link',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """ErrorDetail - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            code (str): [optional]  # noqa: E501
            number (int): [optional]  # noqa: E501
            message (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            fault_code (str): [optional]  # noqa: E501
            fault_sub_code (str): [optional]  # noqa: E501
            help_link (str): [optional]  # noqa: E501
            refers_to (str): [optional]  # noqa: E501
            severity (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """ErrorDetail - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            code (str): [optional]  # noqa: E501
            number (int): [optional]  # noqa: E501
            message (str): [optional]  # noqa: E501
            description (str): [optional]  # noqa: E501
            fault_code (str): [optional]  # noqa: E501
            fault_sub_code (str): [optional]  # noqa: E501
            help_link (str): [optional]  # noqa: E501
            refers_to (str): [optional]  # noqa: E501
            severity (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
