"""
AvaTax Software Development Kit for Python.

   Copyright 2022 Avalara, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

    AvaTax API
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator) 

@author     Sachin Baijal <sachin.baijal@avalara.com>
@author     Jonathan Wenger <jonathan.wenger@avalara.com>
@copyright  2022 Avalara, Inc.
@license    https://www.apache.org/licenses/LICENSE-2.0
@version    0.1.1
@link       https://github.com/avadev/AvaTax-REST-V3-Python-SDK
"""

import re  # noqa: F401
import sys  # noqa: F401

from Avalara.SDK.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from Avalara.SDK.exceptions import ApiAttributeError


def lazy_import():
    from Avalara.SDK.model.Avatax.V2.cover_letter_model import CoverLetterModel
    from Avalara.SDK.model.Avatax.V2.customer_model import CustomerModel
    globals()['CoverLetterModel'] = CoverLetterModel
    globals()['CustomerModel'] = CustomerModel


class CertExpressInvitationModel(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('delivery_method',): {
            'EMAIL': "Email",
            'FAX': "Fax",
            'DOWNLOAD': "Download",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'id': (int,),  # noqa: E501
            'company_id': (int,),  # noqa: E501
            'recipient': (str,),  # noqa: E501
            'customer_code': (str,),  # noqa: E501
            'customer': (CustomerModel,),  # noqa: E501
            'cover_letter': (CoverLetterModel,),  # noqa: E501
            'email_status': (str,),  # noqa: E501
            'cover_letters_only': (bool,),  # noqa: E501
            'exposure_zones': ([int],),  # noqa: E501
            'exempt_reasons': ([int],),  # noqa: E501
            'delivery_method': (str,),  # noqa: E501
            'message': (str,),  # noqa: E501
            'date': (datetime,),  # noqa: E501
            'request_link': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'id': 'id',  # noqa: E501
        'company_id': 'companyId',  # noqa: E501
        'recipient': 'recipient',  # noqa: E501
        'customer_code': 'customerCode',  # noqa: E501
        'customer': 'customer',  # noqa: E501
        'cover_letter': 'coverLetter',  # noqa: E501
        'email_status': 'emailStatus',  # noqa: E501
        'cover_letters_only': 'coverLettersOnly',  # noqa: E501
        'exposure_zones': 'exposureZones',  # noqa: E501
        'exempt_reasons': 'exemptReasons',  # noqa: E501
        'delivery_method': 'deliveryMethod',  # noqa: E501
        'message': 'message',  # noqa: E501
        'date': 'date',  # noqa: E501
        'request_link': 'requestLink',  # noqa: E501
    }

    read_only_vars = {
        'id',  # noqa: E501
        'email_status',  # noqa: E501
        'cover_letters_only',  # noqa: E501
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """CertExpressInvitationModel - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): A unique ID number representing this CertExpress invitation.. [optional]  # noqa: E501
            company_id (int): The unique ID number of the AvaTax company that sent this invitation.. [optional]  # noqa: E501
            recipient (str): The email address to which this invitation was sent.  If this invitation was presented as a weblink, this value will be null.. [optional]  # noqa: E501
            customer_code (str): The unique code of the customer that received this invitation.  Note: This field is case sensitive. To have exemption certificates apply, this value should  be the same as the one passed to create a customer.. [optional]  # noqa: E501
            customer (CustomerModel): [optional]  # noqa: E501
            cover_letter (CoverLetterModel): [optional]  # noqa: E501
            email_status (str): The status of the emails associated with this invitation.  If this invitation was sent via email,  this value will change to `Sent` when the email message has been sent.. [optional]  # noqa: E501
            cover_letters_only (bool): True if this invitation contained a cover letter only.. [optional]  # noqa: E501
            exposure_zones ([int]): When an invitation is sent, it contains a list of exposure zones for which the customer is invited to upload  their exemption certificates.  This list contains the ID numbers of the exposure zones identified.                For a list of exposure zones, please call `ListCertificateExposureZones`.. [optional]  # noqa: E501
            exempt_reasons ([int]): The list of exemption reasons identified by this CertExpress invitation.                For a list of reason codes, please call `ListCertificateExemptReasons`.. [optional]  # noqa: E501
            delivery_method (str): Indicates the method that was used to deliver this CertExpress invitation.. [optional]  # noqa: E501
            message (str): The custom message delivered with this invitation.. [optional]  # noqa: E501
            date (datetime): The date of the invitation.. [optional]  # noqa: E501
            request_link (str): The web link (URL) that a customer can click on or visit to begin using this CertExpress invitation.                This value is only usable if the status of this invitation is `Ready` and the request was created with type `Download`.  NOTE: This link usually takes a few minutes to be available.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """CertExpressInvitationModel - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            id (int): A unique ID number representing this CertExpress invitation.. [optional]  # noqa: E501
            company_id (int): The unique ID number of the AvaTax company that sent this invitation.. [optional]  # noqa: E501
            recipient (str): The email address to which this invitation was sent.  If this invitation was presented as a weblink, this value will be null.. [optional]  # noqa: E501
            customer_code (str): The unique code of the customer that received this invitation.  Note: This field is case sensitive. To have exemption certificates apply, this value should  be the same as the one passed to create a customer.. [optional]  # noqa: E501
            customer (CustomerModel): [optional]  # noqa: E501
            cover_letter (CoverLetterModel): [optional]  # noqa: E501
            email_status (str): The status of the emails associated with this invitation.  If this invitation was sent via email,  this value will change to `Sent` when the email message has been sent.. [optional]  # noqa: E501
            cover_letters_only (bool): True if this invitation contained a cover letter only.. [optional]  # noqa: E501
            exposure_zones ([int]): When an invitation is sent, it contains a list of exposure zones for which the customer is invited to upload  their exemption certificates.  This list contains the ID numbers of the exposure zones identified.                For a list of exposure zones, please call `ListCertificateExposureZones`.. [optional]  # noqa: E501
            exempt_reasons ([int]): The list of exemption reasons identified by this CertExpress invitation.                For a list of reason codes, please call `ListCertificateExemptReasons`.. [optional]  # noqa: E501
            delivery_method (str): Indicates the method that was used to deliver this CertExpress invitation.. [optional]  # noqa: E501
            message (str): The custom message delivered with this invitation.. [optional]  # noqa: E501
            date (datetime): The date of the invitation.. [optional]  # noqa: E501
            request_link (str): The web link (URL) that a customer can click on or visit to begin using this CertExpress invitation.                This value is only usable if the status of this invitation is `Ready` and the request was created with type `Download`.  NOTE: This link usually takes a few minutes to be available.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
